export const metadata = {
  title: "Cart Page",
  description: "Generated by create next app",
};

const CartLayout = ({ children }: { children: React.ReactNode }) => {
  return <main>{children}</main>;
};

export default CartLayout;
