import { ReactNode } from "react";

export const metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};

const ProductLayout = ({ children }: { children: ReactNode }) => {
  return <main>{children}</main>;
};

export default ProductLayout;
